backend:
  name: github
  repo: ctrleffive/benfocus
  branch: master
  base_url: https://benfocus.now.sh
  auth_endpoint: api/oauth/begin

media_folder: content/uploads
public_folder: content/uploads

collections:
  - name: work
    label: Work
    folder: content/work
    create: true
    fields:
      - { name: title, label: Title }
